apiVersion: v1
kind: Service
metadata:
  name: esm-game-loader
  labels:
    app: esm-game-loader
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3033
  selector:
    app: esm-game-loader
