apiVersion: apps/v1
kind: Deployment
metadata:
  name: esm-game-loader
  labels:
    app: esm-game-loader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esm-game-loader
  template:
    metadata:
      labels:
        app: esm-game-loader
    spec:
      containers:
      - name: esm-game-loader
        image: registry.digitalocean.com/esm-dev/live-gloader:latest
        env:
        - name: DB_CERT_PATH
          value: /etc/ssl/certs/ca.crt
        - name: DB_CONN_STRING
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: DB_CONN_STRING
        - name: JWK_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_AUDIENCE
        - name: JWK_ISSUER
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_ISSUER
        - name: JWK_URL
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_URL
        - name: LISTEN_ON
          value: 0.0.0.0:3033
        - name: SERVER_TIMEZONE
          value: "0"
        resources: {}
        ports:
        - containerPort: 3033
        volumeMounts:
        - name: pg-ca
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          readOnly: false
      imagePullSecrets:
      - name: registry-esm-dev
      volumes:
        - name: pg-ca
          secret:
            secretName: pg-ca-secret
      