apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkers
  labels:
    app: checkers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkers
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: checkers
    spec:
      containers:
      - name: checkers
        image: registry.digitalocean.com/esm-dev/dev-checkers:latest
        env:
        - name: CHECKER_TIME_WAIT
          value: "60"
        - name: DB_CERT_PATH
          value: /etc/ssl/certs/ca.crt
        - name: DB_CONN_STRING
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: DB_CONN_STRING
        - name: FCM_KEY
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: FCM_KEY
        - name: SERVER_TIMEZONE
          value: "8"
        resources: {}
        volumeMounts:
        - name: pg-ca
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          readOnly: true
      imagePullSecrets:
      - name: registry-esm-dev
      volumes:
        - name: pg-ca
          secret:
            secretName: pg-ca-secret