apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-standby
  labels:
    app: pg-standby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-standby
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pg-standby
    spec:
      containers:
      - name: pg-standby
        image: registry.digitalocean.com/esm-dev/live-pg-standby:latest
        env:
        - name: PG_REP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: PG_REP_PASSWORD
        - name: PG_REP_USER
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: PG_REP_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: POSTGRES_USER
        - name: PG_MASTER_HOST
          value: pg-master
        - name: PG_MASTER_PORT
          value: '5432'
        args: 
        - gosu 
        - postgres 
        - postgres 
        - -c
        - listen_addresses=*
        - -c
        - port=5432
        - -c
        - ssl=on
        - -c
        - ssl_cert_file=/var/lib/postgresql/server.crt
        - -c
        - ssl_key_file=/var/lib/postgresql/server.key
        - -c
        - ssl_ca_file=/var/lib/postgresql/ca.crt
        - -c
        - ssl_crl_file=/var/lib/postgresql/ca.crl
        - -c
        - primary_conninfo=user=$(PG_REP_USER) password=$(PG_REP_PASSWORD) channel_binding=prefer host=pg-master port=5432 sslmode=prefer sslcompression=0 ssl_min_protocol_version=TLSv1.2 gssencmode=prefer krbsrvname=postgres target_session_attrs=any
        
        ports:
          - containerPort: 5432
        resources: 
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 250m
      imagePullSecrets:
      - name: registry-esm-dev