apiVersion: apps/v1
kind: Deployment
metadata:
  name: esm-stripe
  labels:
    app: esm-stripe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esm-stripe
  template:
    metadata:
      labels:
        app: esm-stripe
    spec:
      containers:
      - name: esm-stripe
        image: registry.digitalocean.com/esm-dev/live-stripe:latest
        env:
        - name: PORT
          value: "4242"
        - name: STRIPE_SECRET
          valueFrom:
            configMapKeyRef:
              name: stripe-config
              key: STRIPE_SECRET
        resources: {}
        ports:
        - containerPort: 4242
      imagePullSecrets:
      - name: registry-esm-dev
          