apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #volumeName: pv-certbot
  storageClassName: do-block-storage