apiVersion: v1
kind: Service
metadata:
  name: esm-homeapp
  labels:
    app: esm-homeapp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3388
  selector:
    app: esm-homeapp
