apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: registry.digitalocean.com/esm-dev/live-pg-pool:latest
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: POSTGRES_PASSWORD
        resources: {}
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config