apiVersion: apps/v1
kind: Deployment
metadata:
  name: esmservice
  labels:
    app: esmservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esmservice
  strategy: {}
  template:
    metadata:
      labels:
        app: esmservice
    spec:
      containers:
      - name: esmservice
        image: registry.digitalocean.com/esm-dev/dev-service:latest
        env:
        - name: BEFORE_LOGIN_TOKEN
          value: Bearer before-login-token
        - name: CHECKER_TIME_WAIT
          value: "60"
        - name: DB_CERT_PATH
          value: /etc/ssl/certs/ca.crt
        - name: DB_CONN_STRING
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: DB_CONN_STRING
        - name: FCM_KEY
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: FCM_KEY
        - name: JWK_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_AUDIENCE
        - name: JWK_ISSUER
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_ISSUER
        - name: JWK_URL
          valueFrom:
            configMapKeyRef:
              name: google-config
              key: JWK_URL
        - name: LISTEN_ON
          value: 0.0.0.0:50051
        - name: SERVER_TIMEZONE
          value: "0"
        - name: STRIPE_SECRET
          valueFrom:
            configMapKeyRef:
              name: stripe-config
              key: STRIPE_SECRET
        resources: {}
        ports:
        - containerPort: 50051
          
        volumeMounts:
        - name: pg-ca
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          readOnly: true
      imagePullSecrets:
      - name: registry-esm-dev
      volumes:
        - name: pg-ca
          secret:
            secretName: pg-ca-secret
