apiVersion: apps/v1
kind: Deployment
metadata:
  name: certbot
  labels:
    app: certbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certbot
  template:
    metadata:
      labels:
        app: certbot
    spec:
      serviceAccountName: certbot
      containers:
      - name: certbot
        image: thienpow/certbot:latest
        env:
        - name: LISTEN_ON
          value: 0.0.0.0:3099
        - name: WWW_FOLDER
          value: www
        - name: SERVICE_NAME
          value: certbot
        - name: CERTBOT_PARAMS
          value: "--domains dev-api.esportsmini.com -d dev-homeapp.esportsmini.com -d dev-gloader.esportsmini.com -d dev-api.esportsmini.com -d dev-admin.esportsmini.com -d dev-stripe.esportsmini.com"
        - name: CERT_NAME
          value: dev-api.esportsmini.com-0001
        - name: CERT_EMAIL
          value: thienpow@gmail.com
        resources: {}
        ports:
        - containerPort: 80
        - containerPort: 3099
        volumeMounts:
        - name: etc-letsencrypt-folder
          mountPath: /etc/letsencrypt
      imagePullSecrets:
      - name: registry-esm-dev
      volumes:
      - name: etc-letsencrypt-folder
        persistentVolumeClaim:
          claimName: certbot-pvc
      