apiVersion: v1
kind: Service
metadata:
  name: esm-admin
  labels:
    app: esm-admin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3030
  selector:
    app: esm-admin
