apiVersion: v1
kind: Service
metadata:
  name: esmservice
  labels:
    app: esmservice
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: esmservice