apiVersion: v1
kind: Service
metadata:
  name: frontenvoy
  labels:
    app: frontenvoy
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: postgres
      port: 15438
      targetPort: 15432
  selector:
    app: frontenvoy