apiVersion: v1
kind: Service
metadata:
  name: grpc-web-proxy
  labels:
    app: grpc-web-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8087
  selector:
    app: grpc-web-proxy
