kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-pg-master
  annotations:
    # fake it by indicating this is provisioned dynamically, so the system
    # works properly
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
spec:
  storageClassName: do-block-storage
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: dbf6b056-cdd7-11eb-b561-0a58ac14a28a # run `doctl compute volume list` to check for the handler
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"