apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-pg-master
  storageClassName: do-block-storage